# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-app
  title: Python Flask template
  description: Privisions a minimal Flask application
spec:
  owner: development
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component Name
          type: string
          description: Provide a component (microservice) name
        environment:
          title: Environment
          type: string
          description: Provide an environment where this component will be deployed
          enum:
            - dev
            - prod

  steps: []