# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-app
  title: Python Flask template
  description: Privisions a minimal Flask application
spec:
  owner: development
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component Name
          type: string
          description: Provide a component (microservice) name
        environment:
          title: Environment
          type: string
          description: Provide an environment where this component will be deployed
          enum:
            - dev
            - prod

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.component_id }}
          environment: ${{ parameters.env }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: https://github.com/julianomontini/${{ parameters.component_id }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'